### PR TITLE
fix: use fontawesome svg icons to reduce bundlesize

### LINKED ISSUE #177: minimize font-awesome size
it seems to occupy too much space

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

### PR DESCRIPTION
**Pull request by njzjz**
this fixes #177

### CODE REVIEW

File: src/plugins/vuetify.js [hunk 1]
```diff
@@ -1,8 +1,13 @@
 import Vue from 'vue'
 import Vuetify from 'vuetify/lib'
 import 'vuetify/src/stylus/app.styl'
-import '@fortawesome/fontawesome-free/css/all.css'
+import { library } from '@fortawesome/fontawesome-svg-core'
+import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
+import { faAtom, faBalanceScale, faFlask, faChartBar, faBurn, faQuestion, faCog } from '@fortawesome/free-solid-svg-icons'
+
+Vue.component('font-awesome-icon', FontAwesomeIcon)
+library.add(fas)
```
Comment (njzjz) [inline src/plugins/vuetify.js]:
```suggestion
library.add(faAtom, faBalanceScale, faFlask, faChartBar, faBurn, faQuestion, faCog)
```

File: src/plugins/vuetify.js [hunk 2]
```diff
@@ -1,8 +1,55 @@
...
+      props: {
+        icon: ['fas', 'question']
+      }
+    },
+    'cog': {
+      component: FontAwesomeIcon,
+      props: {
+        icon: ['fas', 'cog']
+      }
+    },
```
Comment (njzjz) [inline src/plugins/vuetify.js]:
```suggestion
    }
```

File: src/plugins/vuetify.js [hunk 3]
```diff
@@ -1,8 +1,55 @@
...
+      props: {
+        icon: ['fas', 'question']
+      }
+    },
+    'cog': {
+      component: FontAwesomeIcon,
+      props: {
+        icon: ['fas', 'cog']
+      }
+    }
```
Comment (njzjz) [inline src/plugins/vuetify.js]:
```suggestion
    }
  }
```

File: src/App.vue [hunk 4]
```diff
@@ -4,7 +4,7 @@
       <v-list dense>
         <v-list-tile v-for="(tool, i) in tools" :key="i" :to="tool.to">
           <v-list-tile-action>
-            <v-icon>{{tool.icon}}</v-icon>
+            <font-awesome-icon icon="{{tool.icon}}"/>
```
Comment (njzjz) [inline src/App.vue]:
```suggestion
            <font-awesome-icon v-icon="tool.icon"/>
```

File: src/components/index.vue [hunk 5]
```diff
@@ -14,7 +14,7 @@
         <v-layout row wrap class="justify-center">
           <v-flex v-for="(tool, i) in tools" :key="i" class="mx-3" style="width:200px;">
             <v-btn :to="tool.to" block dark color="purple lighten-1">
-              <v-icon class="mx-1">{{ tool.icon }}</v-icon>
+              <font-awesome-icon class="mx-1" icon="{{ tool.icon }}"/>
```
Comment (njzjz) [inline src/components/index.vue]:
```suggestion
              <font-awesome-icon class="mx-1" v-icon="tool.icon"/>
```

File: src/components/index.vue [hunk 6]
```diff
@@ -14,7 +14,7 @@
         <v-layout row wrap class="justify-center">
           <v-flex v-for="(tool, i) in tools" :key="i" class="mx-3" style="width:200px;">
             <v-btn :to="tool.to" block dark color="purple lighten-1">
-              <v-icon class="mx-1">{{ tool.icon }}</v-icon>
+              <font-awesome-icon class="mx-1" v-icon="tool.icon"/>
```
Comment (njzjz) [inline src/components/index.vue]:
```suggestion
              <v-icon class="mx-1">$vuetify.icons.{{ tool.icon }}</v-icon>
```

File: src/App.vue [hunk 7]
```diff
@@ -4,7 +4,7 @@
       <v-list dense>
         <v-list-tile v-for="(tool, i) in tools" :key="i" :to="tool.to">
           <v-list-tile-action>
-            <v-icon>{{tool.icon}}</v-icon>
+            <font-awesome-icon v-icon="tool.icon"/>
```
Comment (njzjz) [inline src/App.vue]:
```suggestion
            <v-icon>$vuetify.icons.{{ tool.icon }}</v-icon>
```

File: src/components/index.vue [hunk 8]
```diff
@@ -14,7 +14,7 @@
         <v-layout row wrap class="justify-center">
           <v-flex v-for="(tool, i) in tools" :key="i" class="mx-3" style="width:200px;">
             <v-btn :to="tool.to" block dark color="purple lighten-1">
-              <v-icon class="mx-1">{{ tool.icon }}</v-icon>
+              <v-icon class="mx-1">$vuetify.icons.{{ tool.icon }}</v-icon>
```
Comment (njzjz) [inline src/components/index.vue]:
```suggestion
              <font-awesome-icon class="mx-1" :icon="tool.icon"/>
```
